/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Saber
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        NewItem = new javax.swing.JMenuItem();
        OpenItem = new javax.swing.JMenuItem();
        SaveItem = new javax.swing.JMenuItem();
        SaveAsItem = new javax.swing.JMenuItem();
        ExitItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        SAllItem = new javax.swing.JMenuItem();
        CutItem = new javax.swing.JMenuItem();
        CopyItem = new javax.swing.JMenuItem();
        PasteItem = new javax.swing.JMenuItem();
        UndoItem = new javax.swing.JMenuItem();
        RedoItem = new javax.swing.JMenuItem();
        FindItem = new javax.swing.JMenuItem();
        ReplaceItem = new javax.swing.JMenuItem();
        ChaneFontItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        FileMenu.setText("File");

        NewItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewItem.setText("New");
        NewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewItemActionPerformed(evt);
            }
        });
        FileMenu.add(NewItem);

        OpenItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenItem.setText("Open");
        FileMenu.add(OpenItem);

        SaveItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveItem.setText("Save");
        FileMenu.add(SaveItem);

        SaveAsItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        SaveAsItem.setText("Save As");
        FileMenu.add(SaveAsItem);

        ExitItem.setText("Exit");
        FileMenu.add(ExitItem);

        jMenuBar1.add(FileMenu);

        jMenu2.setText("Edit");

        SAllItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        SAllItem.setText("Select All");
        jMenu2.add(SAllItem);

        CutItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        CutItem.setText("Cut");
        jMenu2.add(CutItem);

        CopyItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CopyItem.setText("Copy");
        jMenu2.add(CopyItem);

        PasteItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        PasteItem.setText("Paste");
        PasteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteItemActionPerformed(evt);
            }
        });
        jMenu2.add(PasteItem);

        UndoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        UndoItem.setText("Undo");
        jMenu2.add(UndoItem);

        RedoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        RedoItem.setText("Redo");
        jMenu2.add(RedoItem);

        FindItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        FindItem.setText("Find");
        FindItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindItemActionPerformed(evt);
            }
        });
        jMenu2.add(FindItem);

        ReplaceItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        ReplaceItem.setText("Replace");
        jMenu2.add(ReplaceItem);

        ChaneFontItem.setText("Change Font");
        jMenu2.add(ChaneFontItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindItemActionPerformed

    private void PasteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasteItemActionPerformed

    private void NewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    public JMenuItem getChaneFontItem() {
        return ChaneFontItem;
    }

    public void setChaneFontItem(JMenuItem ChaneFontItem) {
        this.ChaneFontItem = ChaneFontItem;
    }

    public JMenuItem getCopyItem() {
        return CopyItem;
    }

    public void setCopyItem(JMenuItem CopyItem) {
        this.CopyItem = CopyItem;
    }

    public JMenuItem getCutItem() {
        return CutItem;
    }

    public void setCutItem(JMenuItem CutItem) {
        this.CutItem = CutItem;
    }

    public JMenuItem getExitItem() {
        return ExitItem;
    }

    public void setExitItem(JMenuItem ExitItem) {
        this.ExitItem = ExitItem;
    }

    public JMenu getFileMenu() {
        return FileMenu;
    }

    public void setFileMenu(JMenu FileMenu) {
        this.FileMenu = FileMenu;
    }

    public JMenuItem getFindItem() {
        return FindItem;
    }

    public void setFindItem(JMenuItem FindItem) {
        this.FindItem = FindItem;
    }

    public JMenuItem getNewItem() {
        return NewItem;
    }

    public void setNewItem(JMenuItem NewItem) {
        this.NewItem = NewItem;
    }

    public JMenuItem getOpenItem() {
        return OpenItem;
    }

    public void setOpenItem(JMenuItem OpenItem) {
        this.OpenItem = OpenItem;
    }

    public JMenuItem getPasteItem() {
        return PasteItem;
    }

    public void setPasteItem(JMenuItem PasteItem) {
        this.PasteItem = PasteItem;
    }

    public JMenuItem getRedoItem() {
        return RedoItem;
    }

    public void setRedoItem(JMenuItem RedoItem) {
        this.RedoItem = RedoItem;
    }

    public JMenuItem getReplaceItem() {
        return ReplaceItem;
    }

    public void setReplaceItem(JMenuItem ReplaceItem) {
        this.ReplaceItem = ReplaceItem;
    }

    public JMenuItem getSAllItem() {
        return SAllItem;
    }

    public void setSAllItem(JMenuItem SAllItem) {
        this.SAllItem = SAllItem;
    }

    public JMenuItem getSaveAsItem() {
        return SaveAsItem;
    }

    public void setSaveAsItem(JMenuItem SaveAsItem) {
        this.SaveAsItem = SaveAsItem;
    }

    public JMenuItem getSaveItem() {
        return SaveItem;
    }

    public void setSaveItem(JMenuItem SaveItem) {
        this.SaveItem = SaveItem;
    }

    public JMenuItem getUndoItem() {
        return UndoItem;
    }

    public void setUndoItem(JMenuItem UndoItem) {
        this.UndoItem = UndoItem;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChaneFontItem;
    private javax.swing.JMenuItem CopyItem;
    private javax.swing.JMenuItem CutItem;
    private javax.swing.JMenuItem ExitItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem FindItem;
    private javax.swing.JMenuItem NewItem;
    private javax.swing.JMenuItem OpenItem;
    private javax.swing.JMenuItem PasteItem;
    private javax.swing.JMenuItem RedoItem;
    private javax.swing.JMenuItem ReplaceItem;
    private javax.swing.JMenuItem SAllItem;
    private javax.swing.JMenuItem SaveAsItem;
    private javax.swing.JMenuItem SaveItem;
    private javax.swing.JMenuItem UndoItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
